### ISSUE TITLE
Incompatible enum changes are allowed even in FULL compatibility Mode

### ISSUE THREAD

**Issue by filosganga** [aiven/karapace#524]
# What happened?

Trying to evolve this schema:
```
{
  "name": "Foo",
  "namespace": "com.example",
  "type": "record",
  "fields": [
    {
        "name": "myEnum",
        "type": {
            "type": "enum",
            "name": "MyEnum",
            "symbols": ["A", "B", "C"]
        }
    }
  ]
}
```

To this schema:
```
{
  "name": "Foo",
  "namespace": "com.example",
  "type": "record",
  "fields": [
    {
        "name": "myEnum",
        "type": {
            "type": "enum",
            "name": "MyEnum",
            "symbols": ["A", "C"]
        }
    }
  ]
}
```

Or this schema:
```
{
  "name": "Foo",
  "namespace": "com.example",
  "type": "record",
  "fields": [
    {
        "name": "myEnum",
        "type": {
            "type": "enum",
            "name": "MyEnum",
            "symbols": ["A", "B", "C", "D"]
        }
    }
  ]
}
```

Is allowed, while shouldn't be allowed in FULL compatibility mode.

Also, the compatibility check, returns true, when it should return false.

# What did you expect to happen?

Karapace should reject the schema update with incompatibility enum changes.

# What else do we need to know?

The very same issue was present in the confluent schema-registry, and raised in this bug:
https://github.com/confluentinc/schema-registry/issues/880

**Comment by NotoriousPyro** [comment]
It seems this is likely a bug of `avro`: https://pypi.org/project/avro/


```python
recordEnumABSchema = parse_avro_schema_definition("""{
  "name": "Foo",
  "namespace": "com.example",
  "type": "record",
  "fields": [
    {
        "name": "myEnum",
        "type": {
            "type": "enum",
            "name": "MyEnum",
            "symbols": ["A", "B"]
        }
    }
  ]
}""")
recordEnumABCSchema = parse_avro_schema_definition("""{
  "name": "Foo",
  "namespace": "com.example",
  "type": "record",
  "fields": [
    {
        "name": "myEnum",
        "type": {
            "type": "enum",
            "name": "MyEnum",
            "symbols": ["A", "B", "C"]
        }
    }
  ]
}""")

[...]
    msg = "changing enum values is NOT a backwards compatible change"
    res = ReaderWriterCompatibilityChecker().get_compatibility(recordEnumABCSchema, recordEnumABSchema)
    assert not schemas_are_compatible(res, SchemaCompatibilityResult(SchemaCompatibilityType.compatible)), msg
```

Fails

**Comment by tvainika** [comment]
`BACKWARD` schema compatibility means data written with old schema works with new schema. E.g. data written with ABC enum schema is not backward compatible with AB enum schema because value C might be used. Also Avro Python implementation detects this correctly with Avro version Karapace is using currently (1.11.1+)

`ReaderWriterCompatibilityChecker().get_compatibility(recordEnumABSchema, recordEnumABCSchema)` returns incompatbility.

Karapace test suite has tests/integration/test_schema.py::test_enum_schema_field_add_compatibility which requires FULL compatibility in very similar case, but also unit test tests/unit/test_avro_compatibility.py::test_schema_compatibility_missing_enum_symbols which detects incompatibility there, which look a bit conflicting tests in this case.
